### ISSUE TITLE
ease in out 触发动画时NavigationBar会变黑闪过撒。

### ISSUE THREAD

**Issue by Jinxiansen** [CoderJackyHuang/HYBControllerTransitions#3]

**Comment by CoderJackyHuang** [comment]
这个我意味到的，原因是没有获取屏幕截图，但是获取屏幕截图会只有是fromView可以得到，toView只是view，在没有出现之前是没有得到它的导航条的，所以就不能得到带导航的截图！效果自然就没有那么好了！

下一版本会修正这个问题！

原始邮件
发件人:晋先森notifications@github.com
收件人:CoderJackyHuang/HYBControllerTransitionsHYBControllerTransitions@noreply.github.com
发送时间:2016年4月8日(周五) 11:18
主题:[CoderJackyHuang/HYBControllerTransitions] ease in out 触发动画时NavigationBar会变黑闪过撒。 (#3)

**Comment by Jinxiansen** [comment]
thinks.

**Comment by CoderJackyHuang** [comment]
可能解决不了这个问题，从当前viewcontroller->presentto->another view controller，此时可以拿到当前viewcontroller+导航条的截图，但是another view controller的导航是没有拿得到的，所以得不到整个截图，效果就无法得到那么好的！

**Comment by Jinxiansen** [comment]
那真是太遗憾了！

**Comment by CoderJackyHuang** [comment]
我尝试其他办法解决下！但是不确定能否做到！
